//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app'
};

//page
import Blog from './blog';

const AboutPage = () => {
  return <Blog />;
};

export default AboutPage;
