//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Checkout',
  description: 'Generated by create next app'
};

//page
import Checkout from './checkout';

const AboutPage = () => {
  return <Checkout />;
};

export default AboutPage;
