//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Contact',
  description: 'Generated by create next app'
};

//page
import Contact from './contact';

const ContactPage = () => {
  return <Contact />;
};

export default ContactPage;
