//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Shopping cart',
  description: 'Generated by create next app'
};

//page
import Cart from './cart';

const AboutPage = () => {
  return <Cart />;
};

export default AboutPage;
