import AppProvider from './app';
import './globals.css';

//font
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
