import AppProvider from './app';
import './globals.css';

//font
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Organic Food',
  description: 'Generated by create next app'
};

//component
import Header from '@/components/layout/Header';
import Search from '@/components/layout/Search';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Header />
          <Search />
          <Navbar />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
