//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Category',
  description: 'Generated by create next app'
};

//page
import Category from './category';

const AboutPage = () => {
  return <Category />;
};

export default AboutPage;
