//meta
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app'
};

//page
import About from './about';

const AboutPage = () => {
  return <About />;
};

export default AboutPage;
